#FROM ubuntu:latest
#LABEL authors="Dell"
#
#ENTRYPOINT ["top", "-b"]

# Generated by chat gtp
# Use an official OpenJDK runtime as a parent image
#FROM openjdk:17-jdk-slim
#
## Set the working directory inside the container
#WORKDIR /app
#
## Copy the application jar file to the container
#COPY target/your-application.jar /app/application.jar
#
## Expose the port the app runs on
#EXPOSE 5000
#
## Run the application
#CMD ["java", "-jar", "/app/application.jar"]

#FROM openjdk:17-jdk-alpine
FROM openjdk:17-jdk-slim
ARG JAR_FILE=target/*.jar
COPY ./target/polls-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 5000
ENTRYPOINT ["java", "-jar", "/app.jar"]

